### ISSUE TITLE
unix build problems from case issues

### ISSUE THREAD

**Issue by joequant** [quigleyj97/jupyterlab-spreadsheet#8]
I'm getting build errors when I run webpack

$ webpack
ModuleNotFoundError: Module not found: Error: Can't resolve './widgetfactory' in '/usr/share/jupyter/lab/staging/node_modules/jupyterlab-spre\
adsheet/lib'
    at factory.create (/usr/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:2825:7
    at /usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:393:1)
    at hook.callAsync (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)

**Comment by erriapo** [comment]
@quigleyj97 I think there is a problem with the package on npm.js.
I forked your code & could install it. Using the existence package fails with the same error reported by OP.

**Comment by quigleyj97** [comment]
@erriapo Thanks for following up. You're right, looks like the NPM package is invalid. It builds fine on Windows because Windows paths are case-insensitive, whereas most *nix platforms are not. Further, it appears the WSL box I was using for testing Linux was pulling in an old version without me noticing.

I'll get a fix out shortly, and will update when it's published.

**Comment by quigleyj97** [comment]
Alright, you should be all set. I'll add some more comprehensive CI so that I don't get caught out by this in the future. Thanks for reporting this issue!
